#!/usr/bin/env python3

import gi
gi.require_version("Gtk", "3.0")
gi.require_version("GtkSource", "4")

from _thirdParty import load_third_party_libs
load_third_party_libs()

from gi.repository import Gtk
from MainWindow import MyWindow


win = MyWindow()
win.show_all()
win.present()
Gtk.main()
